services:
  - type: web
    name: myanmar-music
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python3 -m MYANMARMUSIC
    autoDeploy: true

    envVars:
      API_ID: 
        value: 30566096
      API_HASH: 
        value: 571416932b7adcd28b5e69b2cd3d34b7
      API_KEY:
        sync: false
      BOT_TOKEN:
        sync: false
      MONGO_DB_URI: 
        value: mongodb+srv://pusers:nycreation@nycreation.pd4klp1.mongodb.net/?retryWrites=true&w=majority&appName=NYCREATION
      OWNER_ID:
        value: 8315544720
      OWNER_USERNAME:
        value: HANTHAR999
      BOT_USERNAME:
        value: HANTHAR1999_Bot
      UPSTREAM_REPO:
        value: https://github.com/khithlainhtet/MYANMARMUSIC
      STRING_SESSION:
        sync: false
      GIT_TOKEN:
        sync: false
      HEROKU_API_KEY:
        sync: false
      HEROKU_APP_NAME:
        sync: false
      LOG_GROUP_ID:
        value: -1003522647387
      SUPPORT_GROUP:
        value:https://t.me/myanmarbot_musicupport
      SUPPORT_CHANNEL:
        value:https://t.me/myanmarbot_music
      INSTAGRAM:
        value: https://t.me/HANTHAR_1999
      YOUTUBE:
        value: https://t.me/HANTHAR_27
      GITHUB:
        value: https://github.com/khithlainhtet
      DONATE:
        value:https://t.me/myanmarbot_music/91
      START_IMG_URL:
        sync: false
